# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bc0a3c7f172b82f2dcbc248caf51165dea6e2b8efa9f2a6359366dc2e5d6031ce3ec98e0f6c5ecef58541599c1153964b4494764dbbfcc4dcae6c8420809b7

test:
  secret_key_base: 2ab6d5abfaf662f689c14cfa56ba33404b31855b4f70555d2e7041d532b4d17f882d615eee446748331d29610d9960eebd21f7058277e59a5ce50eefcaba9cf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
